version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: localhost
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    container_name: db-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wp_password
      MYSQL_DATABASE: wordpress
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
      - "33061:33060"
